### ISSUE TITLE
X11 session on Fedora 37 only shows a black screen

### ISSUE THREAD

**Issue by Schneegans** [ddterm/gnome-shell-pod#38]
I recently tried to create a Fedora-37-based container for https://github.com/Schneegans/gnome-shell-pod and failed to properly start GNOME Shell under X11. I then looked into your fork to see if you managed to find a solution for this issue - and AFAIK your Fedora 37 image suffers from the same issue. Here's what I did:

```bash
podman run --rm --cap-add=SYS_NICE,SYS_PTRACE,SETPCAP,NET_RAW,NET_BIND_SERVICE,DAC_READ_SEARCH -ti ghcr.io/ddterm/gnome-shell-pod/fedora-37:2022.11.03.0
```

And then inside the container:

```bash
systemctl --user start "gnome-xsession@:99"
```

If I then inspect the virtual xvfb screen (`podman cp $(podman ps -q -n 1):/run/Xvfb_screen0 . && convert xwd:Xvfb_screen0 capture.jpg && eog capture.jpg`), I only get this:

![capture](https://user-images.githubusercontent.com/829942/199806637-89cec788-457a-4076-b8ba-3b47a8c5b441.jpg)

If I start the wayland session instead (`systemctl --user start "gnome-wayland-nested@:99"`), I can see GNOME Shell properly:

![capture](https://user-images.githubusercontent.com/829942/199807089-e9b0b200-33d1-4f24-aee9-d9a129c9012e.jpg)

With your Fedora-36-based image, both sessions do work.

Can you reproduce this? Do you have an idea what could be causing this? I inspected the output of GNOME Shell and did not find anything suspicious.

Thank you!

**Comment by amezin** [comment]
And exactly the same issue on Ubuntu 22.10.

Also, while the screen is blank, all my tests are passing - from window manager's point of view, there are windows on the screen, and everything is working...

**Comment by amezin** [comment]
Actually, it's not always black screen. For some tests, I get correct screenshots. For some - black screen. It's likely a bug in GNOME Shell + Xvfb.

**Comment by Schneegans** [comment]
I tested it again and it works now! So whatever caused the issue, it seems to have been fixed.

**Comment by amezin** [comment]
Recently I:

- Enabled TCP access to Xorg - I doubt it changed anything for rendering

- Modified the set of installed packages multiple times - which caused updates and rebuilds

So I guess it's fixed by package updates in Fedora
